//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright © 2021 The nvidia-gpu-scheduler Authors.
Copyright 2018 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	"github.com/caden2016/nvidia-gpu-scheduler/api/jsonstruct"

	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GpuNode) DeepCopyInto(out *GpuNode) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GpuNode.
func (in *GpuNode) DeepCopy() *GpuNode {
	if in == nil {
		return nil
	}
	out := new(GpuNode)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GpuNode) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GpuNodeList) DeepCopyInto(out *GpuNodeList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GpuNode, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GpuNodeList.
func (in *GpuNodeList) DeepCopy() *GpuNodeList {
	if in == nil {
		return nil
	}
	out := new(GpuNodeList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GpuNodeList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GpuNodeSpec) DeepCopyInto(out *GpuNodeSpec) {
	*out = *in
	if in.GpuInfos != nil {
		in, out := &in.GpuInfos, &out.GpuInfos
		*out = make(map[string]*jsonstruct.GpuInfo, len(*in))
		for key, val := range *in {
			var outVal *jsonstruct.GpuInfo
			if val == nil {
				(*out)[key] = nil
			} else {
				in, out := &val, &outVal
				*out = new(jsonstruct.GpuInfo)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.Models != nil {
		in, out := &in.Models, &out.Models
		*out = make(map[string][]string, len(*in))
		for key, val := range *in {
			var outVal []string
			if val == nil {
				(*out)[key] = nil
			} else {
				in, out := &val, &outVal
				*out = make([]string, len(*in))
				copy(*out, *in)
			}
			(*out)[key] = outVal
		}
	}
	if in.NodeDeviceInUse != nil {
		in, out := &in.NodeDeviceInUse, &out.NodeDeviceInUse
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	in.ReportTime.DeepCopyInto(&out.ReportTime)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GpuNodeSpec.
func (in *GpuNodeSpec) DeepCopy() *GpuNodeSpec {
	if in == nil {
		return nil
	}
	out := new(GpuNodeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GpuNodeStatus) DeepCopyInto(out *GpuNodeStatus) {
	*out = *in
	in.LastHealthyTime.DeepCopyInto(&out.LastHealthyTime)
	in.LastTransitionTime.DeepCopyInto(&out.LastTransitionTime)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GpuNodeStatus.
func (in *GpuNodeStatus) DeepCopy() *GpuNodeStatus {
	if in == nil {
		return nil
	}
	out := new(GpuNodeStatus)
	in.DeepCopyInto(out)
	return out
}
