apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  name: {{ include "nvidia-gpu-scheduler.apiservice.name" . }}
spec:
  group: {{ .Values.apigroup }}
  groupPriorityMinimum: 100
  insecureSkipTLSVerify: true
  service:
    name: {{ include "nvidia-gpu-scheduler.fullname" . }}
    namespace: {{ .Release.Namespace }}
    port: 443
  version: {{ .Values.apiversion }}
  versionPriority: 100