apiVersion: v1
kind: Service
metadata:
  name: {{ include "nvidia-gpu-scheduler.fullname" . }}
  labels:
    {{- include "nvidia-gpu-scheduler.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: https
  selector:
    {{- include "nvidia-gpu-scheduler.selectorLabels" . | nindent 4 }}
