//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright © 2021 The nvidia-gpu-scheduler Authors.
Copyright 2018 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	"github.com/caden2016/nvidia-gpu-scheduler/api/jsonstruct"

	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContainerResourcesDetail) DeepCopyInto(out *ContainerResourcesDetail) {
	*out = *in
	if in.DeviceInfo != nil {
		in, out := &in.DeviceInfo, &out.DeviceInfo
		*out = make([]*jsonstruct.GpuInfo, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(jsonstruct.GpuInfo)
				**out = **in
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContainerResourcesDetail.
func (in *ContainerResourcesDetail) DeepCopy() *ContainerResourcesDetail {
	if in == nil {
		return nil
	}
	out := new(ContainerResourcesDetail)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GpuPod) DeepCopyInto(out *GpuPod) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GpuPod.
func (in *GpuPod) DeepCopy() *GpuPod {
	if in == nil {
		return nil
	}
	out := new(GpuPod)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GpuPod) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GpuPodList) DeepCopyInto(out *GpuPodList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GpuPod, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GpuPodList.
func (in *GpuPodList) DeepCopy() *GpuPodList {
	if in == nil {
		return nil
	}
	out := new(GpuPodList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GpuPodList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GpuPodSpec) DeepCopyInto(out *GpuPodSpec) {
	*out = *in
	if in.ContainerDevices != nil {
		in, out := &in.ContainerDevices, &out.ContainerDevices
		*out = make([]ContainerResourcesDetail, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GpuPodSpec.
func (in *GpuPodSpec) DeepCopy() *GpuPodSpec {
	if in == nil {
		return nil
	}
	out := new(GpuPodSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GpuPodStatus) DeepCopyInto(out *GpuPodStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GpuPodStatus.
func (in *GpuPodStatus) DeepCopy() *GpuPodStatus {
	if in == nil {
		return nil
	}
	out := new(GpuPodStatus)
	in.DeepCopyInto(out)
	return out
}
